backend:
  repo: VeikkoAJ/eraleijonat.github.io
  branch: master
  name: github
  api_root: https://api.github.com
  site_domain: https://veikkoaj.github.io/eraleijonat.github.io/
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: netlify-cms/

media_folder: "docs/public/"
public_folder: "docs/public/"
publish_mode: editorial_workflow