backend:
  repo: VeikkoAJ/eraleijonat.github.io
  branch: master
  name: git-gateway
  api_root: https://api.github.com
  site_domain: iridescent-sfogliatella-7c9ed3.netlify.app
  base_url: https://api.netlify.com
  auth_endpoint: auth
  cms_label_prefix: netlify-cms/

media_folder: "docs/public/"
public_folder: "docs/public/"
publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    files:
    - name: index
      label: "Etusivu"
      file: docs/index.md
      create: false
      delete: false
      fields: 
        - {label: Title, name: title, widget: string}
        - {label: Intro, name: intro, widget: markdown}
        - {label: Time table, name: timeTable, widget: markdown}